/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Compras;

import Data.CarrosDAO;
import Data.Moto;
import Data.MotoDAO;
import beans.Carros;
import beans.Motos;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class Venda_Motos extends javax.swing.JFrame {

    /**
     * Creates new form Venda_Motos
     */
    public Venda_Motos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtPesquisarMotos = new javax.swing.JTextField();
        BtnPesquisarMoto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FormaPagamentoMotos = new javax.swing.JComboBox<>();
        ComboBoxMotos = new javax.swing.JComboBox<>();
        QuantidadeMotos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtnCalcularMotos = new javax.swing.JButton();
        BtnCarros = new javax.swing.JButton();
        TotalMotos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BrnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 144, 144));

        jPanel2.setBackground(new java.awt.Color(178, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Motos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel2.setText("Escolha sua Moto");

        BtnPesquisarMoto.setText("Pesquisar");
        BtnPesquisarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarMotoActionPerformed(evt);
            }
        });

        jLabel3.setText("Qual A forma de pagamento");

        FormaPagamentoMotos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão de Crédito", "Boleto Bancário", "PIX", "PicPay" }));

        ComboBoxMotos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yamaha v-max", "polaris rzr", "honda gold wing", "bmw s", "Volvo S90", "harley-davidson cvo", "honda cb", "bmw r", "brp can-am", "harley-davidson fat boy", "harley-davidson street", "HARLEY-DAVIDSON BREAKOUT", "ducati panigale", "harley-davidson softail", "suzuki hayabusa" }));

        jLabel4.setText("Quantidade");

        BtnCalcularMotos.setBackground(new java.awt.Color(153, 0, 0));
        BtnCalcularMotos.setForeground(new java.awt.Color(255, 0, 0));
        BtnCalcularMotos.setText("Calcular");
        BtnCalcularMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularMotosActionPerformed(evt);
            }
        });

        BtnCarros.setBackground(new java.awt.Color(153, 0, 0));
        BtnCarros.setForeground(new java.awt.Color(255, 0, 0));
        BtnCarros.setText("Carros");
        BtnCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarrosActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        BtnCancelar.setBackground(new java.awt.Color(153, 0, 0));
        BtnCancelar.setForeground(new java.awt.Color(255, 0, 0));
        BtnCancelar.setText("Cancelar compra");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BrnComprar.setBackground(new java.awt.Color(153, 0, 0));
        BrnComprar.setForeground(new java.awt.Color(255, 0, 0));
        BrnComprar.setText("Finalizar compra");
        BrnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ComboBoxMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(QuantidadeMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BtnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TotalMotos))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnCalcularMotos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnCarros))
                                    .addComponent(BrnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxtPesquisarMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnPesquisarMoto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(FormaPagamentoMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisarMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisarMoto)
                    .addComponent(FormaPagamentoMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantidadeMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCarros)
                    .addComponent(BtnCalcularMotos))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TotalMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrnComprar)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalcularMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularMotosActionPerformed
        calc();
    }//GEN-LAST:event_BtnCalcularMotosActionPerformed

    private void BtnCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarrosActionPerformed
    dispose();
    Venda_Carros Carros = new Venda_Carros();
    Carros.setVisible(true);
    }//GEN-LAST:event_BtnCarrosActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BrnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrnComprarActionPerformed
    String Produtos = ComboBoxMotos.getSelectedItem().toString();
String Pagamento = FormaPagamentoMotos.getSelectedItem().toString();

        Motos motos = new Motos();
            MotoDAO motosdao = new MotoDAO();
            boolean status;
            int resposta;
            
            motos.setProduto(Produtos);
            motos.setQuantidade(QuantidadeMotos.getText());
            motos.setFormaDePagamento(Pagamento);
            motos.setTotal(TotalMotos.getText());
            motosdao = new MotoDAO();
            
            status = motosdao.conectar();
            if(status == false){
                JOptionPane.showMessageDialog(null,"Erro de conexão");
            }else{
                resposta = motosdao.salvar(motos);
                if(resposta == 1){
                    JOptionPane.showMessageDialog(null,"Dados incluidos com sucesso");
                    //limpar os campos
                    TotalMotos.setText("");
                    QuantidadeMotos.requestFocus();
                }else if (resposta ==1062){
                    JOptionPane.showMessageDialog(null,"A Compra já foi Feita");   
                }else{
                    JOptionPane.showMessageDialog(null,"Não foi possível inserir os dados! Por favor, verifique valores digitados!");
                }
                motosdao.desconectar();
    } 
    calc();
    dispose();
    Comprar_efetuada_com_Suscesso compra = new Comprar_efetuada_com_Suscesso();
    compra.setVisible(true);
    }//GEN-LAST:event_BrnComprarActionPerformed

    private void BtnPesquisarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarMotoActionPerformed
            String NomeMoto = TxtPesquisarMotos.getText();
        MotoDAO motosDAO = new MotoDAO();
        Moto motos = motosDAO.getMotoNome(NomeMoto);
        if (motos == null) {
            JOptionPane.showMessageDialog(this, "produto não encontrado!");
        } else {

            ComboBoxMotos.setSelectedItem(motos.getProduto());
        }
    }//GEN-LAST:event_BtnPesquisarMotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda_Motos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda_Motos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda_Motos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda_Motos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda_Motos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrnComprar;
    private javax.swing.JButton BtnCalcularMotos;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnCarros;
    private javax.swing.JButton BtnPesquisarMoto;
    private javax.swing.JComboBox<String> ComboBoxMotos;
    private javax.swing.JComboBox<String> FormaPagamentoMotos;
    private javax.swing.JTextField QuantidadeMotos;
    private javax.swing.JTextField TotalMotos;
    private javax.swing.JTextField TxtPesquisarMotos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
public void calc(){
        double quantidade = Double.parseDouble(QuantidadeMotos.getText());  

        double produto1 = 205700.00;
        double produto2 = 179990.00;
        double produto3 = 174900.00;
        double produto4 = 155900.00;
        double produto5 = 675950.00;
        double produto6 = 146900.00;
        double produto7 = 140000.00;
        double produto8 = 129900.00;
        double produto9 = 129000.00;
        double produto10 = 124900.00;
        double produto11= 122990.00;
        double produto12 = 118900.00;
        double produto13 = 118900.00;
        double produto14= 109990.00;
        double produto15 = 109000.00;
         
        
    if(ComboBoxMotos.getSelectedItem().equals("yamaha v-max")){
       String Resultado1;
        double res1;
        res1 = (quantidade * produto1);
        Resultado1 = String.valueOf(res1);
        TotalMotos.setText(Resultado1);
        String add1 = String.valueOf(produto1);
        }
     if(ComboBoxMotos.getSelectedItem().equals("polaris rzr")){
        String Resultado2;
        double res2;
        res2 = (quantidade * produto2);
        Resultado2 = String.valueOf(res2);
        TotalMotos.setText(Resultado2);
        String add2 = String.valueOf(produto2);
        }
     if(ComboBoxMotos.getSelectedItem().equals("honda gold wing")){
        String Resultado3;
        double res3;
        res3 = (quantidade * produto3);
        Resultado3 = String.valueOf(res3);
        TotalMotos.setText(Resultado3);
        String add3 = String.valueOf(produto3);
        }
    if(ComboBoxMotos.getSelectedItem().equals("bmw s")){
        String Resultado4;
        double res4;
        res4 = (quantidade * produto4);
        Resultado4 = String.valueOf(res4);
        TotalMotos.setText(Resultado4);
        String add4 = String.valueOf(produto4);
        }
     if(ComboBoxMotos.getSelectedItem().equals("Volvo S90")){
        String Resultado5;
        double res5;
        res5 = (quantidade * produto5);
        Resultado5 = String.valueOf(res5);
        TotalMotos.setText(Resultado5);
        String add5 = String.valueOf(produto5);
        }
     if(ComboBoxMotos.getSelectedItem().equals("harley-davidson cvo")){
        String Resultado6;
        double res6;
        res6 = (quantidade * produto6);
        Resultado6 = String.valueOf(res6);
        TotalMotos.setText(Resultado6);
        String add6 = String.valueOf(produto6);
        }
    if(ComboBoxMotos.getSelectedItem().equals("honda cb")){
        String Resultado7;
        double res7;
        res7 = (quantidade * produto7);
        Resultado7 = String.valueOf(res7);
        TotalMotos.setText(Resultado7);
        String add7 = String.valueOf(produto7);
        }
     if(ComboBoxMotos.getSelectedItem().equals("bmw r")){
        String Resultado8;
        double res8;
        res8 = (quantidade * produto8);
        Resultado8 = String.valueOf(res8);
        TotalMotos.setText(Resultado8);
        String add8 = String.valueOf(produto8);
        }
     if(ComboBoxMotos.getSelectedItem().equals("brp can-am.8 Mi")){
        String Resultado9;
        double res9;
        res9 = (quantidade * produto9);
        Resultado9 = String.valueOf(res9);
        TotalMotos.setText(Resultado9);
        String add9 = String.valueOf(produto9);
        }
    if(ComboBoxMotos.getSelectedItem().equals("harley-davidson fat boy")){
       String Resultado10;
        double res10;
        res10 = (quantidade * produto10);
        Resultado10 = String.valueOf(res10);
        TotalMotos.setText(Resultado10);
        String add10 = String.valueOf(produto10);
        }
     if(ComboBoxMotos.getSelectedItem().equals("harley-davidson street")){
       String Resultado11;
        double res11;
        res11 = (quantidade * produto11);
        Resultado11 = String.valueOf(res11);
        TotalMotos.setText(Resultado11);
        String add11 = String.valueOf(produto11);
        }
     if(ComboBoxMotos.getSelectedItem().equals("HARLEY-DAVIDSON BREAKOUT")){
       String Resultado12;
        double res12;
        res12 = (quantidade * produto12);
        Resultado12 = String.valueOf(res12);
        TotalMotos.setText(Resultado12);
        String add12 = String.valueOf(produto12);
        }
    if(ComboBoxMotos.getSelectedItem().equals("ducati panigale")){
       String Resultado13;
        double res13;
        res13 = (quantidade * produto13);
        Resultado13 = String.valueOf(res13);
        TotalMotos.setText(Resultado13);
        String add13 = String.valueOf(produto13);
        }
     if(ComboBoxMotos.getSelectedItem().equals("harley-davidson softail")){
       String Resultado14;
        double res14;
        res14 = (quantidade * produto14);
        Resultado14 = String.valueOf(res14);
        TotalMotos.setText(Resultado14);
        String add14 = String.valueOf(produto14);
        }
     if(ComboBoxMotos.getSelectedItem().equals("suzuki hayabusa")){
       String Resultado15;
        double res15;
        res15 = (quantidade * produto15);
        Resultado15 = String.valueOf(res15);
        TotalMotos.setText(Resultado15);
        String add15 = String.valueOf(produto15);
}
}
}
